server:
    port: 9446
spring:
    application:
        name: SpringBootRest
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        password: 786786
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: SHAHUL
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.OracleDialect
                format_sql: true
        show-sql: true